/* start module: pyjsdl.locals */
$pyjs['loaded_modules']['pyjsdl.locals'] = function (__mod_name__) {
	if($pyjs['loaded_modules']['pyjsdl.locals']['__was_initialized__']) return $pyjs['loaded_modules']['pyjsdl.locals'];
	if(typeof $pyjs['loaded_modules']['pyjsdl'] == 'undefined' || !$pyjs['loaded_modules']['pyjsdl']['__was_initialized__']) $p['___import___']('pyjsdl', null);
	var $m = $pyjs['loaded_modules']['pyjsdl.locals'];
	$m['__repr__'] = function() { return '<module: pyjsdl.locals>'; };
	$m['__was_initialized__'] = true;
	if ((__mod_name__ === null) || (typeof __mod_name__ == 'undefined')) __mod_name__ = 'pyjsdl.locals';
	$m['__name__'] = __mod_name__;
	$m.__track_lines__ = new Array();
	$pyjs['loaded_modules']['pyjsdl']['locals'] = $pyjs['loaded_modules']['pyjsdl.locals'];
	try {
		$m.__track_lines__[1] = 'pyjsdl.locals.py, line 1:\n    #Pyjsdl - Copyright (C) 2013 James Garnon <http://gatc.ca/>';
		$m.__track_lines__[7] = 'pyjsdl.locals.py, line 7:\n    KMOD_ALT = 4';
		$m.__track_lines__[8] = 'pyjsdl.locals.py, line 8:\n    KMOD_CAPS = 0';
		$m.__track_lines__[9] = 'pyjsdl.locals.py, line 9:\n    KMOD_CTRL = 2';
		$m.__track_lines__[10] = 'pyjsdl.locals.py, line 10:\n    KMOD_LALT = 4';
		$m.__track_lines__[11] = 'pyjsdl.locals.py, line 11:\n    KMOD_LCTRL = 2';
		$m.__track_lines__[12] = 'pyjsdl.locals.py, line 12:\n    KMOD_LMETA = 0';
		$m.__track_lines__[13] = 'pyjsdl.locals.py, line 13:\n    KMOD_LSHIFT = 1';
		$m.__track_lines__[14] = 'pyjsdl.locals.py, line 14:\n    KMOD_META = 0';
		$m.__track_lines__[15] = 'pyjsdl.locals.py, line 15:\n    KMOD_MODE = 0';
		$m.__track_lines__[16] = 'pyjsdl.locals.py, line 16:\n    KMOD_NONE = 0';
		$m.__track_lines__[17] = 'pyjsdl.locals.py, line 17:\n    KMOD_NUM = 0';
		$m.__track_lines__[18] = 'pyjsdl.locals.py, line 18:\n    KMOD_RALT = 4';
		$m.__track_lines__[19] = 'pyjsdl.locals.py, line 19:\n    KMOD_RCTRL = 2';
		$m.__track_lines__[20] = 'pyjsdl.locals.py, line 20:\n    KMOD_RMETA = 0';
		$m.__track_lines__[21] = 'pyjsdl.locals.py, line 21:\n    KMOD_RSHIFT = 1';
		$m.__track_lines__[22] = 'pyjsdl.locals.py, line 22:\n    KMOD_SHIFT = 1';
		$m.__track_lines__[23] = 'pyjsdl.locals.py, line 23:\n    K_0 = 48';
		$m.__track_lines__[24] = 'pyjsdl.locals.py, line 24:\n    K_1 = 49';
		$m.__track_lines__[25] = 'pyjsdl.locals.py, line 25:\n    K_2 = 50';
		$m.__track_lines__[26] = 'pyjsdl.locals.py, line 26:\n    K_3 = 51';
		$m.__track_lines__[27] = 'pyjsdl.locals.py, line 27:\n    K_4 = 52';
		$m.__track_lines__[28] = 'pyjsdl.locals.py, line 28:\n    K_5 = 53';
		$m.__track_lines__[29] = 'pyjsdl.locals.py, line 29:\n    K_6 = 54';
		$m.__track_lines__[30] = 'pyjsdl.locals.py, line 30:\n    K_7 = 55';
		$m.__track_lines__[31] = 'pyjsdl.locals.py, line 31:\n    K_8 = 56';
		$m.__track_lines__[32] = 'pyjsdl.locals.py, line 32:\n    K_9 = 57';
		$m.__track_lines__[33] = 'pyjsdl.locals.py, line 33:\n    K_ALT = 18';
		$m.__track_lines__[34] = 'pyjsdl.locals.py, line 34:\n    K_AMPERSAND = 166    #charcode 38, DOM_VK 166';
		$m.__track_lines__[35] = 'pyjsdl.locals.py, line 35:\n    K_ASTERISK = 170     #charcode 42, DOM_VK 170';
		$m.__track_lines__[36] = 'pyjsdl.locals.py, line 36:\n    K_AT = 64';
		$m.__track_lines__[37] = 'pyjsdl.locals.py, line 37:\n    K_BACKQUOTE = 96';
		$m.__track_lines__[38] = 'pyjsdl.locals.py, line 38:\n    K_BACKSLASH = 92';
		$m.__track_lines__[39] = 'pyjsdl.locals.py, line 39:\n    K_BACKSPACE = 8';
		$m.__track_lines__[40] = 'pyjsdl.locals.py, line 40:\n    K_BREAK = 0';
		$m.__track_lines__[41] = 'pyjsdl.locals.py, line 41:\n    K_CAPSLOCK = 20';
		$m.__track_lines__[42] = 'pyjsdl.locals.py, line 42:\n    K_CARET = 94';
		$m.__track_lines__[43] = 'pyjsdl.locals.py, line 43:\n    K_CLEAR = 0';
		$m.__track_lines__[44] = 'pyjsdl.locals.py, line 44:\n    K_COLON = 58';
		$m.__track_lines__[45] = 'pyjsdl.locals.py, line 45:\n    K_COMMA = 188    #charcode 44, DOM_VK 188';
		$m.__track_lines__[46] = 'pyjsdl.locals.py, line 46:\n    K_CTRL = 17';
		$m.__track_lines__[47] = 'pyjsdl.locals.py, line 47:\n    K_DELETE = 46';
		$m.__track_lines__[48] = 'pyjsdl.locals.py, line 48:\n    K_DOLLAR = 164   #charcode 36, DOM_VK 164';
		$m.__track_lines__[49] = 'pyjsdl.locals.py, line 49:\n    K_DOWN = 40';
		$m.__track_lines__[50] = 'pyjsdl.locals.py, line 50:\n    K_END = 35';
		$m.__track_lines__[51] = 'pyjsdl.locals.py, line 51:\n    K_EQUALS = 61';
		$m.__track_lines__[52] = 'pyjsdl.locals.py, line 52:\n    K_ESCAPE = 27';
		$m.__track_lines__[53] = 'pyjsdl.locals.py, line 53:\n    K_EURO = 0';
		$m.__track_lines__[54] = 'pyjsdl.locals.py, line 54:\n    K_EXCLAIM = 161  #charcode 33, DOM_VK 161';
		$m.__track_lines__[55] = 'pyjsdl.locals.py, line 55:\n    K_F1 = 112';
		$m.__track_lines__[56] = 'pyjsdl.locals.py, line 56:\n    K_F2 = 113';
		$m.__track_lines__[57] = 'pyjsdl.locals.py, line 57:\n    K_F3 = 114';
		$m.__track_lines__[58] = 'pyjsdl.locals.py, line 58:\n    K_F4 = 115';
		$m.__track_lines__[59] = 'pyjsdl.locals.py, line 59:\n    K_F5 = 116';
		$m.__track_lines__[60] = 'pyjsdl.locals.py, line 60:\n    K_F6 = 117';
		$m.__track_lines__[61] = 'pyjsdl.locals.py, line 61:\n    K_F7 = 118';
		$m.__track_lines__[62] = 'pyjsdl.locals.py, line 62:\n    K_F8 = 119';
		$m.__track_lines__[63] = 'pyjsdl.locals.py, line 63:\n    K_F9 = 120';
		$m.__track_lines__[64] = 'pyjsdl.locals.py, line 64:\n    K_F10 = 121';
		$m.__track_lines__[65] = 'pyjsdl.locals.py, line 65:\n    K_F11 = 122';
		$m.__track_lines__[66] = 'pyjsdl.locals.py, line 66:\n    K_F12 = 123';
		$m.__track_lines__[67] = 'pyjsdl.locals.py, line 67:\n    K_F13 = 124';
		$m.__track_lines__[68] = 'pyjsdl.locals.py, line 68:\n    K_F14 = 125';
		$m.__track_lines__[69] = 'pyjsdl.locals.py, line 69:\n    K_F15 = 126';
		$m.__track_lines__[70] = 'pyjsdl.locals.py, line 70:\n    K_FIRST = 0';
		$m.__track_lines__[71] = 'pyjsdl.locals.py, line 71:\n    K_GREATER = 62';
		$m.__track_lines__[72] = 'pyjsdl.locals.py, line 72:\n    K_HASH = 163 #charcode 35, DOM_VK 163';
		$m.__track_lines__[73] = 'pyjsdl.locals.py, line 73:\n    K_HELP = 0';
		$m.__track_lines__[74] = 'pyjsdl.locals.py, line 74:\n    K_HOME = 36';
		$m.__track_lines__[75] = 'pyjsdl.locals.py, line 75:\n    K_INSERT = 45';
		$m.__track_lines__[76] = 'pyjsdl.locals.py, line 76:\n    K_KP0 = 96';
		$m.__track_lines__[77] = 'pyjsdl.locals.py, line 77:\n    K_KP1 = 97';
		$m.__track_lines__[78] = 'pyjsdl.locals.py, line 78:\n    K_KP2 = 98';
		$m.__track_lines__[79] = 'pyjsdl.locals.py, line 79:\n    K_KP3 = 99';
		$m.__track_lines__[80] = 'pyjsdl.locals.py, line 80:\n    K_KP4 = 100';
		$m.__track_lines__[81] = 'pyjsdl.locals.py, line 81:\n    K_KP5 = 101';
		$m.__track_lines__[82] = 'pyjsdl.locals.py, line 82:\n    K_KP6 = 102';
		$m.__track_lines__[83] = 'pyjsdl.locals.py, line 83:\n    K_KP7 = 103';
		$m.__track_lines__[84] = 'pyjsdl.locals.py, line 84:\n    K_KP8 = 104';
		$m.__track_lines__[85] = 'pyjsdl.locals.py, line 85:\n    K_KP9 = 105';
		$m.__track_lines__[86] = 'pyjsdl.locals.py, line 86:\n    K_KP_DIVIDE = 0';
		$m.__track_lines__[87] = 'pyjsdl.locals.py, line 87:\n    K_KP_ENTER = 0';
		$m.__track_lines__[88] = 'pyjsdl.locals.py, line 88:\n    K_KP_EQUALS = 0';
		$m.__track_lines__[89] = 'pyjsdl.locals.py, line 89:\n    K_KP_MINUS = 0';
		$m.__track_lines__[90] = 'pyjsdl.locals.py, line 90:\n    K_KP_MULTIPLY = 0';
		$m.__track_lines__[91] = 'pyjsdl.locals.py, line 91:\n    K_KP_PERIOD = 0';
		$m.__track_lines__[92] = 'pyjsdl.locals.py, line 92:\n    K_KP_PLUS = 0';
		$m.__track_lines__[93] = 'pyjsdl.locals.py, line 93:\n    K_LALT = 18';
		$m.__track_lines__[94] = 'pyjsdl.locals.py, line 94:\n    K_LAST = 0';
		$m.__track_lines__[95] = 'pyjsdl.locals.py, line 95:\n    K_LCTRL = 17';
		$m.__track_lines__[96] = 'pyjsdl.locals.py, line 96:\n    K_LEFT = 37';
		$m.__track_lines__[97] = 'pyjsdl.locals.py, line 97:\n    K_LEFTBRACKET = 91';
		$m.__track_lines__[98] = 'pyjsdl.locals.py, line 98:\n    K_LEFTPAREN = 168    #charcode 40, DOM_VK 168';
		$m.__track_lines__[99] = 'pyjsdl.locals.py, line 99:\n    K_LESS = 60';
		$m.__track_lines__[100] = 'pyjsdl.locals.py, line 100:\n    K_LMETA = 0';
		$m.__track_lines__[101] = 'pyjsdl.locals.py, line 101:\n    K_LSHIFT = 16';
		$m.__track_lines__[102] = 'pyjsdl.locals.py, line 102:\n    K_LSUPER = 0';
		$m.__track_lines__[103] = 'pyjsdl.locals.py, line 103:\n    K_MENU = 0';
		$m.__track_lines__[104] = 'pyjsdl.locals.py, line 104:\n    K_MINUS = 173    #charcode 45, DOM_VK 173';
		$m.__track_lines__[105] = 'pyjsdl.locals.py, line 105:\n    K_MODE = 0';
		$m.__track_lines__[106] = 'pyjsdl.locals.py, line 106:\n    K_NUMLOCK = 0';
		$m.__track_lines__[107] = 'pyjsdl.locals.py, line 107:\n    K_PAGEDOWN = 34';
		$m.__track_lines__[108] = 'pyjsdl.locals.py, line 108:\n    K_PAGEUP = 33';
		$m.__track_lines__[109] = 'pyjsdl.locals.py, line 109:\n    K_PAUSE = 19';
		$m.__track_lines__[110] = 'pyjsdl.locals.py, line 110:\n    K_PERIOD = 190   #charcode 46, DOM_VK 190';
		$m.__track_lines__[111] = 'pyjsdl.locals.py, line 111:\n    K_PLUS = 171     #charcode 43, DOM_VK 171';
		$m.__track_lines__[112] = 'pyjsdl.locals.py, line 112:\n    K_POWER = 0';
		$m.__track_lines__[113] = 'pyjsdl.locals.py, line 113:\n    K_PRINT = 42';
		$m.__track_lines__[114] = 'pyjsdl.locals.py, line 114:\n    K_QUESTION = 63';
		$m.__track_lines__[115] = 'pyjsdl.locals.py, line 115:\n    K_QUOTE = 222    #charcode 39, DOM_VK 222';
		$m.__track_lines__[116] = 'pyjsdl.locals.py, line 116:\n    K_QUOTEDBL = 162 #charcode 34, DOM_VK 162';
		$m.__track_lines__[117] = 'pyjsdl.locals.py, line 117:\n    K_RALT = 18';
		$m.__track_lines__[118] = 'pyjsdl.locals.py, line 118:\n    K_RCTRL = 17';
		$m.__track_lines__[119] = 'pyjsdl.locals.py, line 119:\n    K_RETURN = 13';
		$m.__track_lines__[120] = 'pyjsdl.locals.py, line 120:\n    K_RIGHT = 39';
		$m.__track_lines__[121] = 'pyjsdl.locals.py, line 121:\n    K_RIGHTBRACKET = 93';
		$m.__track_lines__[122] = 'pyjsdl.locals.py, line 122:\n    K_RIGHTPAREN = 169       #charcode 41, DOM_VK 169';
		$m.__track_lines__[123] = 'pyjsdl.locals.py, line 123:\n    K_RMETA = 0';
		$m.__track_lines__[124] = 'pyjsdl.locals.py, line 124:\n    K_RSHIFT = 16';
		$m.__track_lines__[125] = 'pyjsdl.locals.py, line 125:\n    K_RSUPER = 0';
		$m.__track_lines__[126] = 'pyjsdl.locals.py, line 126:\n    K_SCROLLOCK = 0';
		$m.__track_lines__[127] = 'pyjsdl.locals.py, line 127:\n    K_SEMICOLON = 186';
		$m.__track_lines__[128] = 'pyjsdl.locals.py, line 128:\n    K_SHIFT = 16';
		$m.__track_lines__[129] = 'pyjsdl.locals.py, line 129:\n    K_SLASH = 191';
		$m.__track_lines__[130] = 'pyjsdl.locals.py, line 130:\n    K_SPACE = 32';
		$m.__track_lines__[131] = 'pyjsdl.locals.py, line 131:\n    K_SYSREQ = 0';
		$m.__track_lines__[132] = 'pyjsdl.locals.py, line 132:\n    K_TAB = 9';
		$m.__track_lines__[133] = 'pyjsdl.locals.py, line 133:\n    K_UNDERSCORE = 95';
		$m.__track_lines__[134] = 'pyjsdl.locals.py, line 134:\n    K_UNKNOWN = 0';
		$m.__track_lines__[135] = 'pyjsdl.locals.py, line 135:\n    K_UP = 38';
		$m.__track_lines__[136] = 'pyjsdl.locals.py, line 136:\n    K_a = 65';
		$m.__track_lines__[137] = 'pyjsdl.locals.py, line 137:\n    K_b = 66';
		$m.__track_lines__[138] = 'pyjsdl.locals.py, line 138:\n    K_c = 67';
		$m.__track_lines__[139] = 'pyjsdl.locals.py, line 139:\n    K_d = 68';
		$m.__track_lines__[140] = 'pyjsdl.locals.py, line 140:\n    K_e = 69';
		$m.__track_lines__[141] = 'pyjsdl.locals.py, line 141:\n    K_f = 70';
		$m.__track_lines__[142] = 'pyjsdl.locals.py, line 142:\n    K_g = 71';
		$m.__track_lines__[143] = 'pyjsdl.locals.py, line 143:\n    K_h = 72';
		$m.__track_lines__[144] = 'pyjsdl.locals.py, line 144:\n    K_i = 73';
		$m.__track_lines__[145] = 'pyjsdl.locals.py, line 145:\n    K_j = 74';
		$m.__track_lines__[146] = 'pyjsdl.locals.py, line 146:\n    K_k = 75';
		$m.__track_lines__[147] = 'pyjsdl.locals.py, line 147:\n    K_l = 76';
		$m.__track_lines__[148] = 'pyjsdl.locals.py, line 148:\n    K_m = 77';
		$m.__track_lines__[149] = 'pyjsdl.locals.py, line 149:\n    K_n = 78';
		$m.__track_lines__[150] = 'pyjsdl.locals.py, line 150:\n    K_o = 79';
		$m.__track_lines__[151] = 'pyjsdl.locals.py, line 151:\n    K_p = 80';
		$m.__track_lines__[152] = 'pyjsdl.locals.py, line 152:\n    K_q = 81';
		$m.__track_lines__[153] = 'pyjsdl.locals.py, line 153:\n    K_r = 82';
		$m.__track_lines__[154] = 'pyjsdl.locals.py, line 154:\n    K_s = 83';
		$m.__track_lines__[155] = 'pyjsdl.locals.py, line 155:\n    K_t = 84';
		$m.__track_lines__[156] = 'pyjsdl.locals.py, line 156:\n    K_u = 85';
		$m.__track_lines__[157] = 'pyjsdl.locals.py, line 157:\n    K_v = 86';
		$m.__track_lines__[158] = 'pyjsdl.locals.py, line 158:\n    K_w = 87';
		$m.__track_lines__[159] = 'pyjsdl.locals.py, line 159:\n    K_x = 88';
		$m.__track_lines__[160] = 'pyjsdl.locals.py, line 160:\n    K_y = 89';
		$m.__track_lines__[161] = 'pyjsdl.locals.py, line 161:\n    K_z = 90';
		$m.__track_lines__[163] = 'pyjsdl.locals.py, line 163:\n    MOUSEBUTTONDOWN = 5';
		$m.__track_lines__[164] = 'pyjsdl.locals.py, line 164:\n    MOUSEBUTTONUP = 6';
		$m.__track_lines__[165] = 'pyjsdl.locals.py, line 165:\n    MOUSEMOTION = 4';
		$m.__track_lines__[166] = 'pyjsdl.locals.py, line 166:\n    KEYDOWN = 2';
		$m.__track_lines__[167] = 'pyjsdl.locals.py, line 167:\n    KEYUP = 3';
		$m.__track_lines__[169] = 'pyjsdl.locals.py, line 169:\n    ACTIVEEVENT = 1';
		$m.__track_lines__[170] = 'pyjsdl.locals.py, line 170:\n    DOUBLEBUF = 1073741824';
		$m.__track_lines__[171] = 'pyjsdl.locals.py, line 171:\n    FULLSCREEN = -2147483648';
		$m.__track_lines__[172] = 'pyjsdl.locals.py, line 172:\n    HWACCEL = 256';
		$m.__track_lines__[173] = 'pyjsdl.locals.py, line 173:\n    HWPALETTE = 536870912';
		$m.__track_lines__[174] = 'pyjsdl.locals.py, line 174:\n    HWSURFACE = 1';
		$m.__track_lines__[175] = 'pyjsdl.locals.py, line 175:\n    NOEVENT = 0';
		$m.__track_lines__[176] = 'pyjsdl.locals.py, line 176:\n    NOFRAME = 32';
		$m.__track_lines__[177] = 'pyjsdl.locals.py, line 177:\n    NUMEVENTS = 32';
		$m.__track_lines__[178] = 'pyjsdl.locals.py, line 178:\n    OPENGL = 2';
		$m.__track_lines__[179] = 'pyjsdl.locals.py, line 179:\n    QUIT = 12';
		$m.__track_lines__[180] = 'pyjsdl.locals.py, line 180:\n    RESIZABLE = 16';
		$m.__track_lines__[181] = 'pyjsdl.locals.py, line 181:\n    RLEACCEL = 16384';
		$m.__track_lines__[182] = 'pyjsdl.locals.py, line 182:\n    RLEACCELOK = 8192';
		$m.__track_lines__[183] = 'pyjsdl.locals.py, line 183:\n    SRCALPHA = 65536';
		$m.__track_lines__[184] = 'pyjsdl.locals.py, line 184:\n    SRCCOLORKEY = 4096';
		$m.__track_lines__[185] = 'pyjsdl.locals.py, line 185:\n    SWSURFACE = 0';
		$m.__track_lines__[186] = 'pyjsdl.locals.py, line 186:\n    SYSWMEVENT = 13';
		$m.__track_lines__[187] = 'pyjsdl.locals.py, line 187:\n    USEREVENT = 24';

		var $constant_int_0 = new $p['int'](0);
		var $constant_int_1 = new $p['int'](1);
		var $constant_int_2 = new $p['int'](2);
		var $constant_int_3 = new $p['int'](3);
		var $constant_int_4 = new $p['int'](4);
		var $constant_int_5 = new $p['int'](5);
		var $constant_int_6 = new $p['int'](6);
		var $constant_int_8 = new $p['int'](8);
		var $constant_int_9 = new $p['int'](9);
		var $constant_int_12 = new $p['int'](12);
		var $constant_int_13 = new $p['int'](13);
		var $constant_int_16 = new $p['int'](16);
		var $constant_int_17 = new $p['int'](17);
		var $constant_int_18 = new $p['int'](18);
		var $constant_int_19 = new $p['int'](19);
		var $constant_int_20 = new $p['int'](20);
		var $constant_int_24 = new $p['int'](24);
		var $constant_int_27 = new $p['int'](27);
		var $constant_int_1073741824 = new $p['int'](1073741824);
		var $constant_int_32 = new $p['int'](32);
		var $constant_int_33 = new $p['int'](33);
		var $constant_int_34 = new $p['int'](34);
		var $constant_int_35 = new $p['int'](35);
		var $constant_int_36 = new $p['int'](36);
		var $constant_int_37 = new $p['int'](37);
		var $constant_int_38 = new $p['int'](38);
		var $constant_int_39 = new $p['int'](39);
		var $constant_int_40 = new $p['int'](40);
		var $constant_int_42 = new $p['int'](42);
		var $constant_int_45 = new $p['int'](45);
		var $constant_int_46 = new $p['int'](46);
		var $constant_int_16384 = new $p['int'](16384);
		var $constant_int_48 = new $p['int'](48);
		var $constant_int_49 = new $p['int'](49);
		var $constant_int_50 = new $p['int'](50);
		var $constant_int_51 = new $p['int'](51);
		var $constant_int_52 = new $p['int'](52);
		var $constant_int_53 = new $p['int'](53);
		var $constant_int_54 = new $p['int'](54);
		var $constant_int_55 = new $p['int'](55);
		var $constant_int_56 = new $p['int'](56);
		var $constant_int_57 = new $p['int'](57);
		var $constant_int_58 = new $p['int'](58);
		var $constant_int_60 = new $p['int'](60);
		var $constant_int_61 = new $p['int'](61);
		var $constant_int_62 = new $p['int'](62);
		var $constant_int_63 = new $p['int'](63);
		var $constant_int_64 = new $p['int'](64);
		var $constant_int_65 = new $p['int'](65);
		var $constant_int_66 = new $p['int'](66);
		var $constant_int_67 = new $p['int'](67);
		var $constant_int_68 = new $p['int'](68);
		var $constant_int_69 = new $p['int'](69);
		var $constant_int_70 = new $p['int'](70);
		var $constant_int_71 = new $p['int'](71);
		var $constant_int_72 = new $p['int'](72);
		var $constant_int_73 = new $p['int'](73);
		var $constant_int_74 = new $p['int'](74);
		var $constant_int_75 = new $p['int'](75);
		var $constant_int_76 = new $p['int'](76);
		var $constant_int_77 = new $p['int'](77);
		var $constant_int_78 = new $p['int'](78);
		var $constant_int_79 = new $p['int'](79);
		var $constant_int_80 = new $p['int'](80);
		var $constant_int_81 = new $p['int'](81);
		var $constant_int_82 = new $p['int'](82);
		var $constant_int_83 = new $p['int'](83);
		var $constant_int_84 = new $p['int'](84);
		var $constant_int_85 = new $p['int'](85);
		var $constant_int_86 = new $p['int'](86);
		var $constant_int_87 = new $p['int'](87);
		var $constant_int_88 = new $p['int'](88);
		var $constant_int_89 = new $p['int'](89);
		var $constant_int_90 = new $p['int'](90);
		var $constant_int_91 = new $p['int'](91);
		var $constant_int_92 = new $p['int'](92);
		var $constant_int_93 = new $p['int'](93);
		var $constant_int_94 = new $p['int'](94);
		var $constant_int_95 = new $p['int'](95);
		var $constant_int_96 = new $p['int'](96);
		var $constant_int_97 = new $p['int'](97);
		var $constant_int_98 = new $p['int'](98);
		var $constant_int_99 = new $p['int'](99);
		var $constant_int_100 = new $p['int'](100);
		var $constant_int_101 = new $p['int'](101);
		var $constant_int_102 = new $p['int'](102);
		var $constant_int_103 = new $p['int'](103);
		var $constant_int_104 = new $p['int'](104);
		var $constant_int_105 = new $p['int'](105);
		var $constant_int_112 = new $p['int'](112);
		var $constant_int_113 = new $p['int'](113);
		var $constant_int_114 = new $p['int'](114);
		var $constant_int_115 = new $p['int'](115);
		var $constant_int_116 = new $p['int'](116);
		var $constant_int_117 = new $p['int'](117);
		var $constant_int_118 = new $p['int'](118);
		var $constant_int_119 = new $p['int'](119);
		var $constant_int_120 = new $p['int'](120);
		var $constant_int_121 = new $p['int'](121);
		var $constant_int_122 = new $p['int'](122);
		var $constant_int_123 = new $p['int'](123);
		var $constant_int_124 = new $p['int'](124);
		var $constant_int_125 = new $p['int'](125);
		var $constant_int_126 = new $p['int'](126);
		var $constant_int_4096 = new $p['int'](4096);
		var $constant_int_2147483648 = new $p['int'](2147483648);
		var $constant_int_161 = new $p['int'](161);
		var $constant_int_162 = new $p['int'](162);
		var $constant_int_163 = new $p['int'](163);
		var $constant_int_164 = new $p['int'](164);
		var $constant_int_166 = new $p['int'](166);
		var $constant_int_168 = new $p['int'](168);
		var $constant_int_169 = new $p['int'](169);
		var $constant_int_170 = new $p['int'](170);
		var $constant_int_171 = new $p['int'](171);
		var $constant_int_173 = new $p['int'](173);
		var $constant_int_186 = new $p['int'](186);
		var $constant_int_188 = new $p['int'](188);
		var $constant_int_190 = new $p['int'](190);
		var $constant_int_191 = new $p['int'](191);
		var $constant_int_222 = new $p['int'](222);
		var $constant_int_256 = new $p['int'](256);
		var $constant_int_8192 = new $p['int'](8192);
		var $constant_int_536870912 = new $p['int'](536870912);
		var $constant_int_65536 = new $p['int'](65536);
		$pyjs['track']['module']='pyjsdl.locals';
		$pyjs['track']['lineno']=1;
		$pyjs['track']['lineno']=7;
		$m['KMOD_ALT'] = $constant_int_4;
		$pyjs['track']['lineno']=8;
		$m['KMOD_CAPS'] = $constant_int_0;
		$pyjs['track']['lineno']=9;
		$m['KMOD_CTRL'] = $constant_int_2;
		$pyjs['track']['lineno']=10;
		$m['KMOD_LALT'] = $constant_int_4;
		$pyjs['track']['lineno']=11;
		$m['KMOD_LCTRL'] = $constant_int_2;
		$pyjs['track']['lineno']=12;
		$m['KMOD_LMETA'] = $constant_int_0;
		$pyjs['track']['lineno']=13;
		$m['KMOD_LSHIFT'] = $constant_int_1;
		$pyjs['track']['lineno']=14;
		$m['KMOD_META'] = $constant_int_0;
		$pyjs['track']['lineno']=15;
		$m['KMOD_MODE'] = $constant_int_0;
		$pyjs['track']['lineno']=16;
		$m['KMOD_NONE'] = $constant_int_0;
		$pyjs['track']['lineno']=17;
		$m['KMOD_NUM'] = $constant_int_0;
		$pyjs['track']['lineno']=18;
		$m['KMOD_RALT'] = $constant_int_4;
		$pyjs['track']['lineno']=19;
		$m['KMOD_RCTRL'] = $constant_int_2;
		$pyjs['track']['lineno']=20;
		$m['KMOD_RMETA'] = $constant_int_0;
		$pyjs['track']['lineno']=21;
		$m['KMOD_RSHIFT'] = $constant_int_1;
		$pyjs['track']['lineno']=22;
		$m['KMOD_SHIFT'] = $constant_int_1;
		$pyjs['track']['lineno']=23;
		$m['K_0'] = $constant_int_48;
		$pyjs['track']['lineno']=24;
		$m['K_1'] = $constant_int_49;
		$pyjs['track']['lineno']=25;
		$m['K_2'] = $constant_int_50;
		$pyjs['track']['lineno']=26;
		$m['K_3'] = $constant_int_51;
		$pyjs['track']['lineno']=27;
		$m['K_4'] = $constant_int_52;
		$pyjs['track']['lineno']=28;
		$m['K_5'] = $constant_int_53;
		$pyjs['track']['lineno']=29;
		$m['K_6'] = $constant_int_54;
		$pyjs['track']['lineno']=30;
		$m['K_7'] = $constant_int_55;
		$pyjs['track']['lineno']=31;
		$m['K_8'] = $constant_int_56;
		$pyjs['track']['lineno']=32;
		$m['K_9'] = $constant_int_57;
		$pyjs['track']['lineno']=33;
		$m['K_ALT'] = $constant_int_18;
		$pyjs['track']['lineno']=34;
		$m['K_AMPERSAND'] = $constant_int_166;
		$pyjs['track']['lineno']=35;
		$m['K_ASTERISK'] = $constant_int_170;
		$pyjs['track']['lineno']=36;
		$m['K_AT'] = $constant_int_64;
		$pyjs['track']['lineno']=37;
		$m['K_BACKQUOTE'] = $constant_int_96;
		$pyjs['track']['lineno']=38;
		$m['K_BACKSLASH'] = $constant_int_92;
		$pyjs['track']['lineno']=39;
		$m['K_BACKSPACE'] = $constant_int_8;
		$pyjs['track']['lineno']=40;
		$m['K_BREAK'] = $constant_int_0;
		$pyjs['track']['lineno']=41;
		$m['K_CAPSLOCK'] = $constant_int_20;
		$pyjs['track']['lineno']=42;
		$m['K_CARET'] = $constant_int_94;
		$pyjs['track']['lineno']=43;
		$m['K_CLEAR'] = $constant_int_0;
		$pyjs['track']['lineno']=44;
		$m['K_COLON'] = $constant_int_58;
		$pyjs['track']['lineno']=45;
		$m['K_COMMA'] = $constant_int_188;
		$pyjs['track']['lineno']=46;
		$m['K_CTRL'] = $constant_int_17;
		$pyjs['track']['lineno']=47;
		$m['K_DELETE'] = $constant_int_46;
		$pyjs['track']['lineno']=48;
		$m['K_DOLLAR'] = $constant_int_164;
		$pyjs['track']['lineno']=49;
		$m['K_DOWN'] = $constant_int_40;
		$pyjs['track']['lineno']=50;
		$m['K_END'] = $constant_int_35;
		$pyjs['track']['lineno']=51;
		$m['K_EQUALS'] = $constant_int_61;
		$pyjs['track']['lineno']=52;
		$m['K_ESCAPE'] = $constant_int_27;
		$pyjs['track']['lineno']=53;
		$m['K_EURO'] = $constant_int_0;
		$pyjs['track']['lineno']=54;
		$m['K_EXCLAIM'] = $constant_int_161;
		$pyjs['track']['lineno']=55;
		$m['K_F1'] = $constant_int_112;
		$pyjs['track']['lineno']=56;
		$m['K_F2'] = $constant_int_113;
		$pyjs['track']['lineno']=57;
		$m['K_F3'] = $constant_int_114;
		$pyjs['track']['lineno']=58;
		$m['K_F4'] = $constant_int_115;
		$pyjs['track']['lineno']=59;
		$m['K_F5'] = $constant_int_116;
		$pyjs['track']['lineno']=60;
		$m['K_F6'] = $constant_int_117;
		$pyjs['track']['lineno']=61;
		$m['K_F7'] = $constant_int_118;
		$pyjs['track']['lineno']=62;
		$m['K_F8'] = $constant_int_119;
		$pyjs['track']['lineno']=63;
		$m['K_F9'] = $constant_int_120;
		$pyjs['track']['lineno']=64;
		$m['K_F10'] = $constant_int_121;
		$pyjs['track']['lineno']=65;
		$m['K_F11'] = $constant_int_122;
		$pyjs['track']['lineno']=66;
		$m['K_F12'] = $constant_int_123;
		$pyjs['track']['lineno']=67;
		$m['K_F13'] = $constant_int_124;
		$pyjs['track']['lineno']=68;
		$m['K_F14'] = $constant_int_125;
		$pyjs['track']['lineno']=69;
		$m['K_F15'] = $constant_int_126;
		$pyjs['track']['lineno']=70;
		$m['K_FIRST'] = $constant_int_0;
		$pyjs['track']['lineno']=71;
		$m['K_GREATER'] = $constant_int_62;
		$pyjs['track']['lineno']=72;
		$m['K_HASH'] = $constant_int_163;
		$pyjs['track']['lineno']=73;
		$m['K_HELP'] = $constant_int_0;
		$pyjs['track']['lineno']=74;
		$m['K_HOME'] = $constant_int_36;
		$pyjs['track']['lineno']=75;
		$m['K_INSERT'] = $constant_int_45;
		$pyjs['track']['lineno']=76;
		$m['K_KP0'] = $constant_int_96;
		$pyjs['track']['lineno']=77;
		$m['K_KP1'] = $constant_int_97;
		$pyjs['track']['lineno']=78;
		$m['K_KP2'] = $constant_int_98;
		$pyjs['track']['lineno']=79;
		$m['K_KP3'] = $constant_int_99;
		$pyjs['track']['lineno']=80;
		$m['K_KP4'] = $constant_int_100;
		$pyjs['track']['lineno']=81;
		$m['K_KP5'] = $constant_int_101;
		$pyjs['track']['lineno']=82;
		$m['K_KP6'] = $constant_int_102;
		$pyjs['track']['lineno']=83;
		$m['K_KP7'] = $constant_int_103;
		$pyjs['track']['lineno']=84;
		$m['K_KP8'] = $constant_int_104;
		$pyjs['track']['lineno']=85;
		$m['K_KP9'] = $constant_int_105;
		$pyjs['track']['lineno']=86;
		$m['K_KP_DIVIDE'] = $constant_int_0;
		$pyjs['track']['lineno']=87;
		$m['K_KP_ENTER'] = $constant_int_0;
		$pyjs['track']['lineno']=88;
		$m['K_KP_EQUALS'] = $constant_int_0;
		$pyjs['track']['lineno']=89;
		$m['K_KP_MINUS'] = $constant_int_0;
		$pyjs['track']['lineno']=90;
		$m['K_KP_MULTIPLY'] = $constant_int_0;
		$pyjs['track']['lineno']=91;
		$m['K_KP_PERIOD'] = $constant_int_0;
		$pyjs['track']['lineno']=92;
		$m['K_KP_PLUS'] = $constant_int_0;
		$pyjs['track']['lineno']=93;
		$m['K_LALT'] = $constant_int_18;
		$pyjs['track']['lineno']=94;
		$m['K_LAST'] = $constant_int_0;
		$pyjs['track']['lineno']=95;
		$m['K_LCTRL'] = $constant_int_17;
		$pyjs['track']['lineno']=96;
		$m['K_LEFT'] = $constant_int_37;
		$pyjs['track']['lineno']=97;
		$m['K_LEFTBRACKET'] = $constant_int_91;
		$pyjs['track']['lineno']=98;
		$m['K_LEFTPAREN'] = $constant_int_168;
		$pyjs['track']['lineno']=99;
		$m['K_LESS'] = $constant_int_60;
		$pyjs['track']['lineno']=100;
		$m['K_LMETA'] = $constant_int_0;
		$pyjs['track']['lineno']=101;
		$m['K_LSHIFT'] = $constant_int_16;
		$pyjs['track']['lineno']=102;
		$m['K_LSUPER'] = $constant_int_0;
		$pyjs['track']['lineno']=103;
		$m['K_MENU'] = $constant_int_0;
		$pyjs['track']['lineno']=104;
		$m['K_MINUS'] = $constant_int_173;
		$pyjs['track']['lineno']=105;
		$m['K_MODE'] = $constant_int_0;
		$pyjs['track']['lineno']=106;
		$m['K_NUMLOCK'] = $constant_int_0;
		$pyjs['track']['lineno']=107;
		$m['K_PAGEDOWN'] = $constant_int_34;
		$pyjs['track']['lineno']=108;
		$m['K_PAGEUP'] = $constant_int_33;
		$pyjs['track']['lineno']=109;
		$m['K_PAUSE'] = $constant_int_19;
		$pyjs['track']['lineno']=110;
		$m['K_PERIOD'] = $constant_int_190;
		$pyjs['track']['lineno']=111;
		$m['K_PLUS'] = $constant_int_171;
		$pyjs['track']['lineno']=112;
		$m['K_POWER'] = $constant_int_0;
		$pyjs['track']['lineno']=113;
		$m['K_PRINT'] = $constant_int_42;
		$pyjs['track']['lineno']=114;
		$m['K_QUESTION'] = $constant_int_63;
		$pyjs['track']['lineno']=115;
		$m['K_QUOTE'] = $constant_int_222;
		$pyjs['track']['lineno']=116;
		$m['K_QUOTEDBL'] = $constant_int_162;
		$pyjs['track']['lineno']=117;
		$m['K_RALT'] = $constant_int_18;
		$pyjs['track']['lineno']=118;
		$m['K_RCTRL'] = $constant_int_17;
		$pyjs['track']['lineno']=119;
		$m['K_RETURN'] = $constant_int_13;
		$pyjs['track']['lineno']=120;
		$m['K_RIGHT'] = $constant_int_39;
		$pyjs['track']['lineno']=121;
		$m['K_RIGHTBRACKET'] = $constant_int_93;
		$pyjs['track']['lineno']=122;
		$m['K_RIGHTPAREN'] = $constant_int_169;
		$pyjs['track']['lineno']=123;
		$m['K_RMETA'] = $constant_int_0;
		$pyjs['track']['lineno']=124;
		$m['K_RSHIFT'] = $constant_int_16;
		$pyjs['track']['lineno']=125;
		$m['K_RSUPER'] = $constant_int_0;
		$pyjs['track']['lineno']=126;
		$m['K_SCROLLOCK'] = $constant_int_0;
		$pyjs['track']['lineno']=127;
		$m['K_SEMICOLON'] = $constant_int_186;
		$pyjs['track']['lineno']=128;
		$m['K_SHIFT'] = $constant_int_16;
		$pyjs['track']['lineno']=129;
		$m['K_SLASH'] = $constant_int_191;
		$pyjs['track']['lineno']=130;
		$m['K_SPACE'] = $constant_int_32;
		$pyjs['track']['lineno']=131;
		$m['K_SYSREQ'] = $constant_int_0;
		$pyjs['track']['lineno']=132;
		$m['K_TAB'] = $constant_int_9;
		$pyjs['track']['lineno']=133;
		$m['K_UNDERSCORE'] = $constant_int_95;
		$pyjs['track']['lineno']=134;
		$m['K_UNKNOWN'] = $constant_int_0;
		$pyjs['track']['lineno']=135;
		$m['K_UP'] = $constant_int_38;
		$pyjs['track']['lineno']=136;
		$m['K_a'] = $constant_int_65;
		$pyjs['track']['lineno']=137;
		$m['K_b'] = $constant_int_66;
		$pyjs['track']['lineno']=138;
		$m['K_c'] = $constant_int_67;
		$pyjs['track']['lineno']=139;
		$m['K_d'] = $constant_int_68;
		$pyjs['track']['lineno']=140;
		$m['K_e'] = $constant_int_69;
		$pyjs['track']['lineno']=141;
		$m['K_f'] = $constant_int_70;
		$pyjs['track']['lineno']=142;
		$m['K_g'] = $constant_int_71;
		$pyjs['track']['lineno']=143;
		$m['K_h'] = $constant_int_72;
		$pyjs['track']['lineno']=144;
		$m['K_i'] = $constant_int_73;
		$pyjs['track']['lineno']=145;
		$m['K_j'] = $constant_int_74;
		$pyjs['track']['lineno']=146;
		$m['K_k'] = $constant_int_75;
		$pyjs['track']['lineno']=147;
		$m['K_l'] = $constant_int_76;
		$pyjs['track']['lineno']=148;
		$m['K_m'] = $constant_int_77;
		$pyjs['track']['lineno']=149;
		$m['K_n'] = $constant_int_78;
		$pyjs['track']['lineno']=150;
		$m['K_o'] = $constant_int_79;
		$pyjs['track']['lineno']=151;
		$m['K_p'] = $constant_int_80;
		$pyjs['track']['lineno']=152;
		$m['K_q'] = $constant_int_81;
		$pyjs['track']['lineno']=153;
		$m['K_r'] = $constant_int_82;
		$pyjs['track']['lineno']=154;
		$m['K_s'] = $constant_int_83;
		$pyjs['track']['lineno']=155;
		$m['K_t'] = $constant_int_84;
		$pyjs['track']['lineno']=156;
		$m['K_u'] = $constant_int_85;
		$pyjs['track']['lineno']=157;
		$m['K_v'] = $constant_int_86;
		$pyjs['track']['lineno']=158;
		$m['K_w'] = $constant_int_87;
		$pyjs['track']['lineno']=159;
		$m['K_x'] = $constant_int_88;
		$pyjs['track']['lineno']=160;
		$m['K_y'] = $constant_int_89;
		$pyjs['track']['lineno']=161;
		$m['K_z'] = $constant_int_90;
		$pyjs['track']['lineno']=163;
		$m['MOUSEBUTTONDOWN'] = $constant_int_5;
		$pyjs['track']['lineno']=164;
		$m['MOUSEBUTTONUP'] = $constant_int_6;
		$pyjs['track']['lineno']=165;
		$m['MOUSEMOTION'] = $constant_int_4;
		$pyjs['track']['lineno']=166;
		$m['KEYDOWN'] = $constant_int_2;
		$pyjs['track']['lineno']=167;
		$m['KEYUP'] = $constant_int_3;
		$pyjs['track']['lineno']=169;
		$m['ACTIVEEVENT'] = $constant_int_1;
		$pyjs['track']['lineno']=170;
		$m['DOUBLEBUF'] = $constant_int_1073741824;
		$pyjs['track']['lineno']=171;
		$m['FULLSCREEN'] = (typeof ($usub1=$constant_int_2147483648)=='number'?
			-$usub1:
			$p['op_usub']($usub1));
		$pyjs['track']['lineno']=172;
		$m['HWACCEL'] = $constant_int_256;
		$pyjs['track']['lineno']=173;
		$m['HWPALETTE'] = $constant_int_536870912;
		$pyjs['track']['lineno']=174;
		$m['HWSURFACE'] = $constant_int_1;
		$pyjs['track']['lineno']=175;
		$m['NOEVENT'] = $constant_int_0;
		$pyjs['track']['lineno']=176;
		$m['NOFRAME'] = $constant_int_32;
		$pyjs['track']['lineno']=177;
		$m['NUMEVENTS'] = $constant_int_32;
		$pyjs['track']['lineno']=178;
		$m['OPENGL'] = $constant_int_2;
		$pyjs['track']['lineno']=179;
		$m['QUIT'] = $constant_int_12;
		$pyjs['track']['lineno']=180;
		$m['RESIZABLE'] = $constant_int_16;
		$pyjs['track']['lineno']=181;
		$m['RLEACCEL'] = $constant_int_16384;
		$pyjs['track']['lineno']=182;
		$m['RLEACCELOK'] = $constant_int_8192;
		$pyjs['track']['lineno']=183;
		$m['SRCALPHA'] = $constant_int_65536;
		$pyjs['track']['lineno']=184;
		$m['SRCCOLORKEY'] = $constant_int_4096;
		$pyjs['track']['lineno']=185;
		$m['SWSURFACE'] = $constant_int_0;
		$pyjs['track']['lineno']=186;
		$m['SYSWMEVENT'] = $constant_int_13;
		$pyjs['track']['lineno']=187;
		$m['USEREVENT'] = $constant_int_24;
	} catch ($pyjs_attr_err) {throw $p['_errorMapping']($pyjs_attr_err);};
	return this;
}; /* end pyjsdl.locals */


/* end module: pyjsdl.locals */


